# Generated by Django 2.0 on 2021-01-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210126_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Profile_Pic',
            field=models.ImageField(default='', upload_to='Profile_Pics'),
        ),
        migrations.AlterField(
            model_name='gc',
            name='Profile_Pic',
            field=models.ImageField(default='', upload_to='Profile_Pics'),
        ),
        migrations.AlterField(
            model_name='rc',
            name='Profile_Pic',
            field=models.ImageField(default='', upload_to='app/Profile_Pics'),
        ),
    ]
