# Generated by Django 2.0 on 2021-01-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210127_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rc',
            name='Profile_Pic',
            field=models.ImageField(default='', upload_to='Profile_Pics'),
        ),
    ]
