# Generated by Django 2.0 on 2021-01-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210127_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=30)),
                ('Product_Price', models.FloatField()),
                ('Product_Desc', models.TextField()),
                ('Product_Img', models.ImageField(default='', upload_to='Product_Images')),
                ('Current_orders', models.IntegerField(default=0)),
                ('RC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RC')),
            ],
        ),
    ]
