# Generated by Django 2.0 on 2021-02-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Seller_Name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
