# Generated by Django 2.0 on 2021-02-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='Password',
            field=models.CharField(max_length=300),
        ),
    ]
