# Generated by Django 2.0 on 2021-02-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210206_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='gc',
            name='Shop_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='rc',
            name='Company_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
