# Generated by Django 2.0 on 2021-02-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Cust_Cart',
        ),
    ]
