# Generated by Django 2.0 on 2021-02-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210210_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust_cart',
            name='Per_Pro_Price',
        ),
    ]
