# Generated by Django 3.0.4 on 2021-02-19 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_cust_cart_per_pro_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Amount', models.IntegerField(default=0)),
                ('Payment_status', models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING')], default=3)),
                ('Order_id', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('Datetime_of_payment', models.DateTimeField(default=django.utils.timezone.now)),
                ('Razorpay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('Razorpay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('Price', models.FloatField()),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
    ]
