# Generated by Django 3.0.4 on 2021-02-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_order_productinorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Total_Amount',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
