# Generated by Django 3.0.4 on 2021-02-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210219_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Payment_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Total_Amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
