# Generated by Django 3.0.4 on 2021-02-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210219_2232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductInOrder',
            new_name='Product_Order',
        ),
    ]
