# Generated by Django 3.0.4 on 2021-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210219_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_cart',
            name='Total_Amount',
            field=models.IntegerField(default=0),
        ),
    ]
