# Generated by Django 3.0.4 on 2021-02-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210219_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
