# Generated by Django 3.0.4 on 2021-02-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210224_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_order',
            name='Payment_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
