# Generated by Django 3.0.4 on 2021-02-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_product_order_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_order',
            name='Customer_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
