# Generated by Django 3.0.4 on 2021-03-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_product_order_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Invoice_No',
            field=models.BigIntegerField(default=0),
        ),
    ]
