# Generated by Django 3.0.4 on 2021-03-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_order_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Sub_Total_Amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
