# Generated by Django 3.0.4 on 2021-03-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_order_sub_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order',
            name='Price',
            field=models.FloatField(default=0),
        ),
    ]
