# Generated by Django 3.0.4 on 2021-03-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210303_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Sub_Total_Amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='Total_Amount',
            field=models.FloatField(default=0),
        ),
    ]
