# Generated by Django 3.0.4 on 2021-03-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210303_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_ID',
            new_name='User_Master',
        ),
    ]
