# Generated by Django 3.0.4 on 2021-03-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20210308_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gc',
            old_name='GC_ID',
            new_name='User_Master',
        ),
        migrations.RenameField(
            model_name='rc',
            old_name='RC_ID',
            new_name='User_Master',
        ),
    ]
