# Generated by Django 3.0.4 on 2021-03-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210308_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='RC_ID',
            new_name='RC',
        ),
        migrations.RenameField(
            model_name='product_order',
            old_name='RC_ID',
            new_name='RC',
        ),
    ]
