# Generated by Django 3.0.4 on 2021-03-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20210308_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cust_cart',
            old_name='Customer_ID',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='cust_cart',
            old_name='Product_ID',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Customer_ID',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='product_order',
            old_name='Customer_ID',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='product_order',
            old_name='Product_ID',
            new_name='Product',
        ),
    ]
