# Generated by Django 3.0.4 on 2021-03-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210308_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_order',
            old_name='Order_ID',
            new_name='Order',
        ),
    ]
