# Generated by Django 3.0.4 on 2021-03-12 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20210309_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_Active', models.BooleanField()),
                ('Subscription_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Subscription_Amount', models.FloatField(default=0)),
                ('Subscription_Starting_Date', models.DateTimeField()),
                ('Subscription_Ending_Date', models.DateTimeField()),
                ('RC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RC')),
            ],
        ),
    ]
