# Generated by Django 3.0.4 on 2021-03-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Invoice_No',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='Razorpay_order_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='Razorpay_payment_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
